FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o orderapi order-api/cmd/main.go

FROM alpine:3.14

WORKDIR /app

COPY --from=builder /app/orderapi .

ENV POSTGRES_DSN=user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} host=${POSTGRES_HOST} port=${POSTGRES_CONTAINER_PORT} sslmode=disable
ENV API_PORT=${API_CONTAINER_PORT}

# Adicionando usuário não-root
RUN adduser -D -u 1001 appuser
USER appuser

CMD ["./orderapi"]
