name: CD pipeline
on:
  workflow_run:
    workflows: ["CI pipeline"]
    branches: [main]
    types: 
      - completed
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Test
      run: echo "Teste"